import { readFileSync, writeFileSync } from "fs";

const html = readFileSync("dist/index.html", "utf-8");
writeFileSync(
  "api/_widget-html.ts",
  `// Auto-generated by scripts/embed-widget.mjs — do not edit\nexport const WIDGET_HTML = ${JSON.stringify(html)};\n`
);
console.log("Widget HTML embedded into api/_widget-html.ts");
